{% set name = "parselglossy" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 182b92de176d9c0d1a895e8a73834cd87aa6e7ebe053e1c2c57c02a46eaad2fe

build:
  number: 0
  noarch: python
  entry_points:
    - parselglossy = parselglossy.cli:cli
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - click
    - flit >=2,<4
    - networkx
    - pip
    - pyparsing
    - python >=3.6
    - pyyaml
  run:
    - click
    - networkx
    - pyparsing
    - python >=3.6
    - pyyaml

test:
  imports:
    - parselglossy
    - parselglossy.grammars
  commands:
    - parselglossy --help

about:
  home: https://parselglossy.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic input parsing library, speaking in tongues.
  doc_url: https://parselglossy.readthedocs.io
  dev_url: https://github.com/dev-cafe/parselglossy

extra:
  recipe-maintainers:
    - robertodr
    - bast
